version: '3.8'

services:
  dashboard:
    build: .
    ports:
      - "8002:80"
    volumes:
      # Map a local data.json into the container's static html root
      # Replace ./local-data-folder/data.json with the path to your actual JSON file
      - ./data.json:/usr/share/nginx/html/data.json:ro

  api:
    build: ./api
    ports:
      - "3001:3001"
    volumes:
      - ./api/user_feedback.json:/app/user_feedback.json
